#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "vitransfer"
name = "ViTransfer"
description.en = "Video Sharing"
description.fr = "Partage de vidéos"
version = "0.9.6~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-3.0-only"
website = "https://vitransfer.com"
admindoc = "https://www.vitransfer.com/docs"
code = "https://github.com/MansiVisuals/ViTransfer"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "2000M"
ram.build = "1500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.admin_password]
    type = "password"
    ask.en = "Choose an admin password"
    ask.fr = "Choisissez un mot de passe pour l'administrateur"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/MansiVisuals/ViTransfer/archive/refs/tags/v0.9.6.tar.gz"
    sha256 = "5f0e2f52b81de7b4e4a5ec548588c0466733ab0c4058cb49609dc83a11ee38e1"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = [
        "ffmpeg", 
        "fontconfig", 
        "redis-server", 
        "postgresql", 
        "fonts-dejavu",
        "ca-certificates",
        "libssl-dev", 
        "libsndfile1", 
        "giflib-tools", 
        "libgif-dev", 
        "libgif7", 
        "liborc-0.4-dev",
        "libcjson-dev",
        "python3", 
        "python3-pip", 
        "python3-venv"
    ]

    [resources.database]
    type = "postgresql"
    
    [resources.nodejs]
    version = "24"
    
