#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

max_upload_size=50
auth_secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=auth_secret --value="$auth_secret"

ynh_app_setting_set --key=max_upload_size --value=$max_upload_size
max_up=$((max_upload_size * 1024 * 1024))

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
email_smtp_port=587
pwd_reset=true
registration=true
retention=30
doc_storage_driver=$doc_storage_driver

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="papra.config.yaml" --destination="$install_dir/apps/papra-server/papra.config.yaml"

#=================================================
# INSTALLATION
#=================================================

pushd "$install_dir"
	ynh_hide_warnings corepack enable && COREPACK_ENABLE_DOWNLOAD_PROMPT=0 corepack prepare pnpm@latest --activate
	ynh_exec_as_app pnpm install 
	ynh_exec_as_app pnpm -r build
	ynh_exec_as_app mkdir -p apps/papra-server/public
	ynh_exec_as_app cp -r apps/papra-client/dist/* apps/papra-server/public/
	ynh_exec_as_app pnpm store prune
popd

chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Papra Docs" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
