#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

max_upload_size=50
encryption_key=$(ynh_string_random -l 32)
jwt_secret=$(ynh_string_random -l 64)
jwt_refresh_secret=$(ynh_string_random -l 64)
share_token_secret=$(ynh_string_random -l 64)
admin_email=$(ynh_user_get_info --username="$admin" --key=mail)

ynh_app_setting_set --key=max_upload_size --value=$max_upload_size
ynh_app_setting_set --key=encryption_key --value="$encryption_key"
ynh_app_setting_set --key=jwt_secret --value="$jwt_secret"
ynh_app_setting_set --key=jwt_refresh_secret --value="$jwt_refresh_secret"
ynh_app_setting_set --key=share_token_secret --value="$share_token_secret"
ynh_app_setting_set --key=admin_email --value="$admin_email"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALLATION
#=================================================

pushd "$install_dir"
	ynh_exec_as_app npm ci --legacy-peer-deps
	ynh_exec_as_app npm audit --audit-level=high
	ynh_exec_as_app npm run build
    
	python3 -m venv $install_dir/apprise-venv
    ynh_hide_warnings $install_dir/apprise-venv/bin/pip install --no-cache-dir --timeout=120 --upgrade pip wheel 
    ynh_hide_warnings $install_dir/apprise-venv/bin/pip install --no-cache-dir --timeout=120 "filelock>=3.20.3" "virtualenv>=20.36.1" 
    ynh_hide_warnings $install_dir/apprise-venv/bin/pip install --no-cache-dir --timeout=120 apprise==1.9.7 

	ynh_exec_as_app npx prisma migrate deploy
popd

chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" --template="vitransfer.service"
ynh_config_add_systemd --service="$app-worker" --template="worker.service" 

yunohost service add "$app" --description="ViTransfer" --log="/var/log/$app/$app.log"
yunohost service add "$app-worker" --description="ViTransfer Worker" --log="/var/log/$app/$app-worker.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-worker" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
